clear; clc; close all;

%% USER PARAMETERS

battery_mass = 1.66;               % kg 
batt_specific_energy = 248.6;      % Wh/kg
E_batt_capacity = battery_mass * batt_specific_energy;

initial_SOC_fraction = 0.90;     % 90% charged at landing

speed = 0.02;                    % m/s
P_motors = 26;                   % W

P_IMU = 1.5;                     % W
P_UWB = 1.68;                    % W
P_sun_sensor = 0.0759;           % W
P_camera = 0.3135;               % W
P_lidar = 6.5;                   % W
lidar_use_fraction = 0.25;
P_comp = 9;                      % W
P_MCU = 0.072;                   % W

P_heaters = 0.2;                 % W

P_av_travel = P_IMU + P_UWB + P_sun_sensor + P_lidar*lidar_use_fraction + P_comp + P_MCU;
P_av_rest = P_IMU + P_comp;

payload_total_power = 15;        % W
num_of_payloads = 2;

payload_drop_distances = [5000 6000];
charge_start_fraction = 0.20;
charge_stop_fraction  = 0.80;

% total_distance_goal is set automatically from the path after sun_map.mat loads

%% PANEL PROPERTIES

panel_number  = 3;
panel_widths  = [0.25, 0.3, 0.3];
panel_height  = 0.37;

lidar_cutout = 0.06*0.06;

panel_eff   = 0.32;
inc_derate  = 0.95;

%% TIME + SOLAR CONSTANTS

n       = 2847;
Tau     = deg2rad(-1.545);
Y       = 346.71;
t_0     = -1.23;

T_total = 24*14;
dt      = 0.01;
t       = 0:dt:T_total;
N       = length(t);

omega   = 360 / T_total;

%% MOON GEOMETRY

R_moon = 1737400;
L      = deg2rad(-91);
E      = deg2rad(90);

%% SOLAR CONSTANTS

G_sc = 1361;

%% LOAD SUN MAP
% sun_map(path_node, time_step) = 1 (sunlit) or 0 (shadow)
% Generated by build_sun_map.m from the planned path CSV + DEM

load('sun_map.mat', 'sun_map', 'path_x_km', 'path_y_km', 'n_path');

% -----------------------------------------------------------------
% Build cumulative distance along path in METRES.
% path_x_km / path_y_km are in km → convert to metres.
% This lets us map current_distance (m) → nearest path node index.
% -----------------------------------------------------------------
path_x_m = path_x_km * 1000;
path_y_m = path_y_km * 1000;

seg_lengths  = sqrt(diff(path_x_m).^2 + diff(path_y_m).^2);
cum_dist_path = [0; cumsum(seg_lengths)];   % n_path x 1, metres
total_distance_goal = cum_dist_path(end);   % set from actual path length

fprintf('Path loaded: %d nodes, total length %.1f m\n', ...
    n_path, cum_dist_path(end));

%% PANEL GEOMETRY (precompute, unchanged each timestep)

azi_p = linspace(0, 360, panel_number+1);
azi_p(end) = [];
azi_p = deg2rad(azi_p);

theta_dip = acos(R_moon / (R_moon + panel_height));

%% MISSION STATE VARIABLES

SOC      = zeros(1, N);
SOC(1)   = initial_SOC_fraction * E_batt_capacity;

distance = zeros(1, N);

payloads_remaining = num_of_payloads;
next_payload_index = 1;

in_charging    = false;
mission_failed = false;   % permanent - rover cannot recover once SOC hits 0

% Tracking arrays for visualisation
illum_log    = zeros(1, N);   % I_illum at each timestep
charging_log = false(1, N);   % in_charging state at each timestep
P_solar_log  = zeros(1, N);   % actual solar power generated

%% MAIN TIME LOOP
% P_solar is now computed inside the loop because I_illum depends on the
% rover's current position, which changes with time and pauses during charging.

t_lunar_offset = (n - 2831) * 24;

for i = 2:N

    if mission_failed
        distance(i) = distance(i-1);
        SOC(i)      = 0;
        continue
    end

    current_distance = distance(i-1);

    % ---------------------------------
    % FIND CURRENT PATH NODE
    % Map current odometer distance to the closest node on the planned path.
    % The path is traversed in order; we clamp to the last node once done.
    % ---------------------------------
    [~, path_node] = min(abs(cum_dist_path - current_distance));
    path_node = max(1, min(n_path, path_node));

    % ---------------------------------
    % ILLUMINATION AT CURRENT POSITION + TIME
    % sun_map uses the same time index i as the main loop (both use
    % t = 0:dt:T_total with the same dt = 0.01 hr).
    % ---------------------------------
    I_illum = double(sun_map(path_node, i));   % 1 = sunlit, 0 = shadow

    % ---------------------------------
    % SOLAR POWER AT THIS TIMESTEP
    % (moved inside loop so I_illum can vary)
    % ---------------------------------
    ti = t(i);

    delta = Tau * sin(deg2rad(360/Y * (n + ti/24 - t_0)));
    H     = deg2rad(omega * (T_total/2 - (ti + t_lunar_offset)));
    B     = asin(cos(L)*cos(delta)*cos(H) + sin(L)*sin(delta));
    cosB  = cos(B);

    if abs(cosB) > 1e-10
        azi_s = asin(max(-1, min(1, cos(delta)*sin(H)/cosB)));
    else
        azi_s = 0;
    end

    P_total = 0;

    if B > -theta_dip
        for p = 1:panel_number
            cos_theta = cos(B)*cos(azi_s - azi_p(p)) + sin(B)*cos(E);
            if cos_theta > 0
                G_panel    = G_sc * cos_theta * I_illum;
                panel_area = panel_widths(p) * panel_height - lidar_cutout;
                P_total    = P_total + G_panel * panel_area * panel_eff * inc_derate;
            end
        end
    end

    P_solar_now = P_total;

    % ---------------------------------
    % CHECK IF MISSION COMPLETE
    % ---------------------------------
    if current_distance >= total_distance_goal
        driving = false;
    else
        driving = true;
    end

    % ---------------------------------
    % PAYLOAD DROP LOGIC
    % ---------------------------------
    if next_payload_index <= length(payload_drop_distances)
        if current_distance >= payload_drop_distances(next_payload_index)
            payloads_remaining = payloads_remaining - 1;
            next_payload_index = next_payload_index + 1;
        end
    end

    % ---------------------------------
    % SOC-BASED CHARGING LOGIC
    % ---------------------------------
    if ~in_charging && driving && ...
            SOC(i-1) <= charge_start_fraction * E_batt_capacity
        in_charging = true;
    end

    if in_charging && ...
            SOC(i-1) >= charge_stop_fraction * E_batt_capacity
        in_charging    = false;
mission_failed = false;   % permanent - rover cannot recover once SOC hits 0
    end

    % ---------------------------------
    % DETERMINE OPERATING MODE
    % ---------------------------------
    if in_charging
        P_mode      = P_av_rest;
        driving_now = false;
    elseif driving
        P_mode      = P_motors + P_av_travel;
        driving_now = true;
    else
        P_mode      = P_av_rest;
        driving_now = false;
    end

    % ---------------------------------
    % PAYLOAD POWER
    % ---------------------------------
    P_payload = payloads_remaining * (payload_total_power / num_of_payloads);

    % ---------------------------------
    % TOTAL LOAD
    % ---------------------------------
    P_load = P_mode + P_payload + P_heaters;

    % ---------------------------------
    % UPDATE DISTANCE
    % Path only advances when actually driving — pauses during charging.
    % ---------------------------------
    if driving_now
        distance(i) = current_distance + speed * dt * 3600;
    else
        distance(i) = current_distance;
    end

    % ---------------------------------
    % LOG FOR VISUALISATION
    % ---------------------------------
    illum_log(i)    = I_illum;
    charging_log(i) = in_charging;
    P_solar_log(i)  = P_solar_now;

    % ---------------------------------
    % SOC UPDATE
    % ---------------------------------
    P_net  = P_solar_now - P_load;
    SOC(i) = SOC(i-1) + P_net * dt;

    % ---------------------------------
    % BATTERY LIMITS
    % ---------------------------------
    if SOC(i) > E_batt_capacity
        SOC(i) = E_batt_capacity;
    end

    if SOC(i) <= 0
        SOC(i)         = 0;
        mission_failed = true;
        fprintf('Mission failure at t=%.2f hr, distance=%.1f m\n', t(i), distance(i));
    end

end

%% RESULTS

min_SOC = min(SOC);
max_SOC = max(SOC);

fprintf('Minimum SOC (Wh): %.2f\n', min_SOC);
fprintf('Maximum SOC (Wh): %.2f\n', max_SOC);

if mission_failed
    failure_time = t(find(SOC == 0, 1));
    failure_dist = distance(find(SOC == 0, 1));
    fprintf('MISSION FAILURE: battery depleted at t=%.2f hr, d=%.1f m\n', ...
        failure_time, failure_dist);
    fprintf('Rover permanently non-operational after this point.\n');
else
    fprintf('Mission feasible with this battery mass.\n');
end

if distance(end) < total_distance_goal
    fprintf('WARNING: Distance goal not reached (%.1f / %.1f m).\n', ...
        distance(end), total_distance_goal);
else
    fprintf('Distance goal reached.\n');
end

%% PLOTS

% --- Figure 1: SOC vs Time (original) ---
figure;
plot(t, SOC, 'LineWidth', 2)
xlabel('Time [hr]')
ylabel('Battery Energy (Wh)')
title('Battery SOC vs Time')
grid on

% --- Figure 2: Distance vs Time (original) ---
figure;
plot(t, distance, 'LineWidth', 2)
xlabel('Time [hr]')
ylabel('Distance Traveled [m]')
title('Distance vs Time')
grid on

% --- Figure 3: SOC + Illumination/Charging overlay ---
% Grey shading  = rover is in shadow (no solar input)
% Blue shading  = rover has stopped to charge
% Both can overlap: charging stop in shadow is the worst case
figure;
hold on

in_shadow    = illum_log == 0;
shadow_starts = find(diff([0  in_shadow     ]) ==  1);
shadow_ends   = find(diff([   in_shadow   0 ]) == -1);
for k = 1:length(shadow_starts)
    xp = [t(shadow_starts(k)) t(shadow_ends(k)) t(shadow_ends(k)) t(shadow_starts(k))];
    yp = [0 0 E_batt_capacity E_batt_capacity];
    patch(xp, yp, [0.85 0.85 0.85], 'EdgeColor', 'none', 'FaceAlpha', 0.5)
end

charge_starts = find(diff([0  double(charging_log)  ]) ==  1);
charge_ends   = find(diff([   double(charging_log) 0]) == -1);
for k = 1:length(charge_starts)
    xp = [t(charge_starts(k)) t(charge_ends(k)) t(charge_ends(k)) t(charge_starts(k))];
    yp = [0 0 E_batt_capacity E_batt_capacity];
    patch(xp, yp, [0.6 0.8 1.0], 'EdgeColor', 'none', 'FaceAlpha', 0.4)
end

plot(t, SOC, 'k-', 'LineWidth', 2)

h1 = patch(NaN, NaN, [0.85 0.85 0.85], 'EdgeColor', 'none', 'FaceAlpha', 0.5);
h2 = patch(NaN, NaN, [0.6  0.8  1.0 ], 'EdgeColor', 'none', 'FaceAlpha', 0.4);
h3 = plot(NaN, NaN, 'k-', 'LineWidth', 2);
legend([h1 h2 h3], {'In shadow', 'Charging stop', 'SOC'}, 'Location', 'best')
xlabel('Time [hr]')
ylabel('Battery Energy (Wh)')
title('SOC vs Time  |  Grey = shadow, Blue = charging stop')
ylim([0 E_batt_capacity * 1.05])
grid on
hold off

% --- Figure 4: Distance vs Time coloured by illumination ---
% Uses NaN-break technique: just 2 plot calls instead of 33,600.
% NaN inserted wherever the condition is false breaks the line there,
% so each series only draws where it applies.
figure;
hold on

sun_mask    = illum_log == 1;          % logical, length N
shadow_mask = ~sun_mask;

% Build distance vectors with NaN wherever the condition is NOT met
dist_sun    = distance;  dist_sun(shadow_mask) = NaN;
dist_shadow = distance;  dist_shadow(sun_mask) = NaN;

plot(t, dist_sun,    '-', 'Color', [0.95 0.75 0.1], 'LineWidth', 1.5)
plot(t, dist_shadow, '-', 'Color', [0.35 0.35 0.55], 'LineWidth', 1.5)

legend({'Sunlit', 'Shadow'}, 'Location', 'best')
xlabel('Time [hr]')
ylabel('Distance Traveled [m]')
title('Distance vs Time  |  Yellow = sunlit, Blue = shadow')
grid on
hold off