# -*- coding: utf-8 -*-
"""MPA_Global_Planner_Dstar_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeyVzQpLFRHAuCfwXWvSi_Ik9P_n3tH8
"""

import rasterio
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import heapq
from collections import deque
import cv2
from rasterio.windows import from_bounds # for choosing window size
from scipy.io import loadmat
import csv
import math
from pyproj import Transformer
import time
from google.colab import drive # note - I had to switch to using google colab at the end of this project because my laptop stopped working unfortunately

# DIRECTIONS
# 1. Download relevant slope and elevation file at https://pgda.gsfc.nasa.gov/products/90
# 2. Either generate or download illumination_data.mat using Caleb's solar script
# 3. Update the file paths for the lunar DEM .tiff files to match where they are in your computer
# 4. For running a singular run of the full pipeline (mission site selection to final shortest path), use singular_run()
# 5. For running multiple runs of full pipelines with landing error, use multiple_runs()
# 6. Directions for specific inputs are included in both singular_run() and multiple_runs()

drive.mount('/content/drive/')

ELEV_FILE = "/content/drive/MyDrive/capstone_files/data/LDEM_83S_10MPP_ADJ.tiff"
SLOPE_FILE = "/content/drive/MyDrive/ENAE484 Lunar Micro Rover/Mission Planning and Analysis/Lunar Terrain DEM Maps/raw data/LDSM_83S_10MPP_ADJ.tiff"
SUN_FILE = "/content/drive/MyDrive/capstone_files/data/illumination_data.mat"

# creating map
class TerrainWorld:
    def __init__(self, traversable_grid):
        self.grid = traversable_grid
        self.size = traversable_grid.shape[0]

    def is_obstacle(self, x, y):
        return not self.grid[x, y]

INF = float('inf')

# check to make sure there's actually a possible path
def path_exists(grid, start, goal):
    q = deque([start])
    visited = {start}
    while q:
        x, y = q.popleft()
        if (x, y) == goal:
            return True
        for dx in [-1, 0, 1]:
            for dy in [-1, 0, 1]:
                if dx == 0 and dy == 0:
                    continue
                nx, ny = x+dx, y+dy
                if 0 <= nx < grid.size and 0 <= ny < grid.size:
                    if not grid.is_obstacle(nx, ny) and (nx, ny) not in visited:
                        visited.add((nx, ny))
                        q.append((nx, ny))
    return False

def extract_path(planner, world, start_node, goal_node):
    # inits for path
    current = start_node
    last_node = start_node
    path_taken = [current] # append nodes here

    while current != goal_node:
        # look at neighbors and pick the best step
        best_s = None
        min_val = INF

        for s_next in planner.neighbors(current, world):
            # move toward the neighbor that minimizes edge cost + g-value
            val = planner.cost(current, s_next, world) + planner.g.get(s_next, INF)
            if val < min_val:
                min_val = val
                best_s = s_next

        if best_s is None or min_val == INF:
            print("No valid path found!")
            print(f"Current node: {current}, goal: {goal_node}")
            return None

        # advance the path
        current = best_s
        path_taken.append(current)

        # update now pos in planner
        planner.km += planner.heuristic(last_node, current)
        last_node = current
        planner.start = current

    return path_taken

# implementing path algorithm
# D*
class DStarLite:
    def __init__(self, size, start, goal, lander, elevation, illumination):
        # inits
        self.size = size
        self.start = start
        self.goal = goal
        self.lander = lander
        self.elevation = elevation
        self.illumination = illumination
        self.g = {}
        self.rhs = {}
        self.U = []
        self.in_queue = {}
        self.km = 0
        self.time_per_px_s = 200 # 10 m / 0.02 m /s speed

        self.rhs[self.goal] = 0
        initial_key = self.calculate_key(self.goal)
        self.in_queue[self.goal] = initial_key
        heapq.heappush(self.U, (initial_key, self.goal))

    def heuristic(self, a, b):
        dx = abs(a[0] - b[0])
        dy = abs(a[1] - b[1])
        return max(dx, dy) + (math.sqrt(2) - 1) * min(dx, dy)

    def calculate_key(self, s):
        k1 = min(self.g.get(s, INF), self.rhs.get(s,INF)) + self.heuristic(self.start, s) + self.km
        k2 = min(self.g.get(s, INF), self.rhs.get(s,INF))
        return (k1, k2)

    def neighbors(self, s, world):
        x, y = s
        results = []
        for dx in [-1, 0, 1]:
            for dy in [-1, 0, 1]:
                if dx == 0 and dy == 0:
                    continue
                nx, ny = x+dx, y+dy
                if 0 <= nx < self.size and 0 <= ny < self.size:
                    if dx != 0 and dy != 0: # prevent corner cutting
                        if world.is_obstacle(x + dx, y) or world.is_obstacle(x, y + dy):
                            continue
                    results.append((nx, ny))
        return results

    def cost(self, u, v, world):
        # if either is an obstacle, cost is infinite
        if world.is_obstacle(*u) or world.is_obstacle(*v):
            return INF

        # distance cost (diagonal vs straight)
        dx = abs(u[0] - v[0])
        dy = abs(u[1] - v[1])

        if dx == 1 and dy == 1:
            dist_cost = math.sqrt(2)
        else:
            dist_cost = 1

        # LOS penalty
        if fast_line_of_sight(self.elevation, v, self.lander):
            los_penalty = 0 # there is LOS
        else:
            los_penalty = 5

        y, x = v

        # solar illumination penalty
        if self.illumination[y,x] >= 0.2:
            solar_penalty = 0
        else:
            solar_penalty = 5

        return dist_cost + los_penalty + solar_penalty

        # return dist_cost

    def update_vertex(self, u, world):
        if u != self.goal:
            # rhs(u) = min_{s' in nbrs} (c(u, s') + g(s'))
            costs = []
            for s_prime in self.neighbors(u, world):
                costs.append(self.cost(u, s_prime, world) + self.g.get(s_prime, INF))
            self.rhs[u] = min(costs) if costs else INF

        if self.g.get(u, INF) != self.rhs.get(u, INF):
            key = self.calculate_key(u)
            if self.in_queue.get(u) != key:
                self.in_queue[u] = key
                heapq.heappush(self.U, (key, u))
        elif u in self.in_queue:
            del self.in_queue[u]

    def compute_shortest_path(self, world):
        iterations = 0
        while self.U and (
        self.U[0][0] < self.calculate_key(self.start) or
        self.rhs.get(self.start, INF) != self.g.get(self.start, INF)):
            k_old, u = heapq.heappop(self.U)
            k_new = self.calculate_key(u)
            if self.in_queue.get(u) != k_old:
                continue

            iterations += 1
            if iterations >= 100000:
                break
            if iterations % 5000 == 0:
                print(f"D* iteration {iterations}, queue size: {len(self.U)}")
            if k_old < k_new:
                self.in_queue[u] = k_new
                heapq.heappush(self.U, (k_new, u))
            elif self.g.get(u, INF) > self.rhs.get(u, INF):
                self.g[u] = self.rhs[u]
                for s in self.neighbors(u, world):
                    self.update_vertex(s, world)
            else:
                self.g[u] = INF
                self.update_vertex(u, world)
                for s in self.neighbors(u, world):
                    self.update_vertex(s, world)

def load_data(elevation_file, slope_file, region_size):
    # elevation data
    with rasterio.open(elevation_file) as src:
        window = from_bounds(-region_size, -region_size, region_size, region_size, src.transform)
        elevation = src.read(1, window = window)
        el_shape = elevation.shape
        transform = src.window_transform(window)

    # slopes data
    with rasterio.open(slope_file) as src:
        window = from_bounds(-region_size, -region_size, region_size, region_size, src.transform)
        slopes = src.read(1, window = window)

    # solar illumination data
    data = loadmat(SUN_FILE)

    sun = data["all_sun_data"]   # (ny, nx, nt)
    X = data["X"]
    Y = data["Y"]

    # crop to same region size as elevation
    x_min, x_max = -region_size, region_size
    y_min, y_max = -region_size, region_size

    x_mask = (X[0, :] >= x_min) & (X[0, :] <= x_max)
    y_mask = (Y[:, 0] >= y_min) & (Y[:, 0] <= y_max)

    sun_cropped = sun[y_mask, :, :]
    sun_cropped = sun_cropped[:, x_mask, :]

    # resample time slices to match elevation resolutions
    rows, cols = el_shape
    nt = sun_cropped.shape[2]

    sun_resampled = np.zeros((rows, cols, nt))

    for t in range(nt):
        sun_resampled[:, :, t] = cv2.resize(sun_cropped[:, :, t], (cols, rows), interpolation=cv2.INTER_NEAREST)

    # avg sunlight metric
    avg_sun = np.mean(sun_resampled, axis=2)

    return elevation, slopes, sun_resampled, avg_sun, transform

def traversability(elevation, slopes, avg_sun):
    # traversable terrain
    traversable_slopes = slopes < 10

    traversable_sun = avg_sun >= 0.50

    # combine traversable regions
    traversable = traversable_slopes & traversable_sun

    return traversable

def fast_line_of_sight(elevation, point1, point2):
    y0, x0 = point1
    y1, x1 = point2

    z0 = elevation[y0, x0] + 0.042
    z1 = elevation[y1,x1] + 2.5

    dx = x1 - x0
    dy = y1 - y0
    dz = z1 - z0

    num_checks = 15

    # coarse pass
    for i in range(1, num_checks + 1):

        t = i / (num_checks + 1)

        x = int(round(x0 + dx*t))
        y = int(round(y0 + dy*t))

        z_expected = z0 + dz * t
        z_actual = elevation[y, x]

        if z_actual > z_expected:
            return False
    return True

def line_of_sight(elevation, point1, point2):
    y0, x0 = point1
    y1, x1 = point2

    z0 = elevation[y0, x0] + 0.042
    z1 = elevation[y1,x1] + 1

    dx = x1 - x0
    dy = y1 - y0
    dz = z1 - z0

    step_size = int(max(abs(dx), abs(dy)))

    # fine pass
    for i in range(1, step_size):

        if step_size == 0:
            return True

        t = i / step_size

        x = int(round(x0 + dx*t))
        y = int(round(y0 + dy*t))

        z_expected = z0 + dz * t
        z_actual = elevation[y, x]

        if z_actual > z_expected:
            return False

    return True

class GenerateWaypoints:
    def __init__(self, major_axis, minor_axis, traversable_grid, elevation):
        self.major_axis = major_axis
        self.minor_axis = minor_axis
        self.traversable_grid = traversable_grid
        self.elevation = elevation

    ########## FINDS THE MOST VIABLE MISSION REGIONS BASED ON % TRAVERSABILITY AND FLATNESS
    def find_landing_ellipses(self):
        # convert major/minor axis length to pixels
        major_pixels = int((self.major_axis * 1000)/10) # account for 10 m / pixel resolution
        minor_pixels = int((self.minor_axis * 1000)/10)

        a = major_pixels//2 # integer division
        b = minor_pixels//2

        h, w = self.traversable_grid.shape
        viable_sites = []

        y, x = np.ogrid[:h,:w]
        counter = 1

        for cy in range(b, h - b, 500): # center of landing ellipse
            current_y = (y - cy)/b
            for cx in range(a, w - a, 500):
                # distance from center as fraction of ellipse radius
                current_x = (x - cx)/a

                ellipse = (current_x**2 + current_y**2) <= 1 # points that satisfy the ellipse equation are included inside the ellipse

                region_trav = self.traversable_grid[ellipse] # traversability inside ellipse
                region_elev = self.elevation[ellipse]

                trav_percent = np.sum(region_trav)/region_trav.size
                if trav_percent >= 0.90:
                    elev_std = np.std(region_elev)
                    viable_sites.append((cx, cy, float(trav_percent), float(elev_std)))
                    print(f'Viable site #{counter}: {viable_sites[-1]})')
                    counter+=1

        viable_sites.sort(key=lambda s: s[3]) # sort in ascending order
        print(f'MOST VIABLE SITE: {viable_sites[0]})')

        top_n = min(5, len(viable_sites))

        plot = False
        # if plot == True:

        #     cmap = matplotlib.colors.ListedColormap(['black', 'green'])
        #     legend = [matplotlib.patches.Patch(facecolor='green', edgecolor='black', label='Traversable (True)'),
        #             matplotlib.patches.Patch(facecolor='black', edgecolor='black', label='Non-Traversable (False)')]

        #     plt.figure(figsize=(8, 8))
        #     plt.title("Top 5 Viable Landing Ellipses")

        #     # base terrain
        #     plt.imshow(self.traversable_grid, cmap=cmap)
        #     plt.legend(handles=legend, loc='upper right')

        #     # ellipses are overlayed in red
        #     ellipse_overlay = np.zeros((h, w, 4))

        #     for i in range(top_n):
        #         cx, cy, _, _ = viable_sites[i]

        #         current_x = (x - cx) / a
        #         current_y = (y - cy) / b
        #         ellipse = (current_x**2 + current_y**2) <= 1

        #         # Red color with transparency
        #         ellipse_overlay[ellipse] = [1, 0, 0, 0.35]  # R, G, B, Alpha (transparency)
        #         plt.contour(ellipse.astype(int), levels=[0.5], colors='red', linewidths=2)

        #     # Plot overlay
        #     plt.imshow(ellipse_overlay)
        #     plt.xlabel("X Pixel")
        #     plt.ylabel("Y Pixel")
        #     # plt.show()

        return viable_sites

    ######## [THIS IS NO LONGER USED] - CHECKS FOR ELEVATION DIPS BETWEEN ROVER AND LANDER
    def elevation_profile_check(self, elevation, point_a, point_b, max_dip_m, n_samples=10):
        y0, x0 = point_a
        y1, x1 = point_b

        elev_a = elevation[y0, x0]
        elev_b = elevation[y1, x1]
        elev_floor = min(elev_a, elev_b) - max_dip_m  # floor below either endpoint
        elev_ceiling = max(elev_a, elev_b) + max_dip_m
        obstacle_count = 0

        for i in range(1, n_samples): # N samples reduces comp time
            t = i / n_samples
            y = int(round(y0 + (y1 - y0) * t))
            x = int(round(x0 + (x1 - x0) * t))
            if elevation[y, x] < elev_floor:
                return False
            if elevation[y,x] > elev_ceiling:
                return False
            elif self.traversable_grid[y,x] == 0:
                obstacle_count +=1
                if obstacle_count >= 3:
                    return False
        return True

    ######## [THIS IS NO LONGER USED] - ENSURES THAT SPECIFIED REGION AROUND WAYPOINT IS WITHIN DESIRED ELEVATION BAND
    def find_flat_region_mask(self, elevation, mission_site, flat_radius_px=5, max_std_m=3.0):
        from scipy.ndimage import uniform_filter, generic_filter

        cx, cy, __, __ = mission_site
        a = int((self.major_axis * 1000) / 10) // 2
        b = int((self.minor_axis * 1000) / 10) // 2

        h, w = elevation.shape

        # ellipse mask
        Y, X = np.ogrid[:h, :w]
        ellipse_mask = ((X - cx)**2 / a**2) + ((Y - cy)**2 / b**2) <= 1

        # compute local std over a flat_radius_px neighborhood
        kernel_size = flat_radius_px * 2 + 1
        local_mean = uniform_filter(elevation.astype(float), size=kernel_size)
        local_sq_mean = uniform_filter(elevation.astype(float)**2, size=kernel_size)
        local_std = np.sqrt(np.maximum(local_sq_mean - local_mean**2, 0))

        # flat = low local std
        flat_mask = (local_std <= max_std_m) & ellipse_mask

        return flat_mask

    def precompute_los_map_downsampled(self, elevation, lander, mission_site, major_axis, minor_axis, downsample, cache_path=None):
        import os
        ly, lx = lander
        cx, cy, _, _ = mission_site

        if cache_path is None:
            cache_path = f"los_cache_{ly}_{lx}_ds{downsample}_major{major_axis}_minor{minor_axis}.npy"

        if os.path.exists(cache_path):
            print(f"Loading cached LOS map from {cache_path}...")
            return np.load(cache_path)

        print(f"Precomputing LOS map (downsample={downsample})...")
        h, w = elevation.shape

        # determine which pixels to check - only within ellipse + padding
        a_px = int((major_axis * 1000) / 10) // 2
        b_px = int((minor_axis * 1000) / 10) // 2
        pad = 50

        row_min = max(0, cy - b_px - pad)
        row_max = min(h, cy + b_px + pad)
        col_min = max(0, cx - a_px - pad)
        col_max = min(w, cx + a_px + pad)

        los_map = np.zeros((h, w), dtype=bool)

        # iterate only over pixels in the ellipse region
        # but pass FULL elevation to line_of_sight so rays aren't clipped
        for y in range(row_min, row_max, downsample):
            for x in range(col_min, col_max, downsample):
                has_los = line_of_sight(elevation, (y, x), (ly, lx))
                # fill the downsample block
                y_end = min(y + downsample, row_max)
                x_end = min(x + downsample, col_max)
                los_map[y:y_end, x:x_end] = has_los

        print(f"LOS computed for {(row_max-row_min)*(col_max-col_min)//downsample**2} pixels")
        np.save(cache_path, los_map)
        print(f"LOS map saved to {cache_path}")
        return los_map


    ######## WAYPOINT SELECTION FUNCTION BASED ON TRAVERSABILITY AND LOS CRITERIA
    def choose_waypoints(self, sun_avg, distance_range_m, mission_site, start, stop_locations):
        def dist(a, b):
            return np.sqrt((a[0]-b[0])**2 + (a[1]-b[1])**2)

        cx, cy, __, __ = mission_site
        a = int((self.major_axis * 1000)/10)//2
        b = int((self.minor_axis * 1000)/10)//2

        min_sep_px = int(distance_range_m[0]/10)
        max_sep_px = int(distance_range_m[1]/10)

        sun_threshold = 50 # percent
        max_attempts = 20
        attempts = 500

        PRESET_START = start

        for __ in range(max_attempts): # overall waypoint selection loop
            while_counter = 0
            waypoints = []
            last_dist = 0

            # choose start
            if PRESET_START == False:
              for i in range(attempts):
                  x = np.random.randint(cx-a, cx+a)
                  y = np.random.randint(cy-b, cy+b)

                  if ((x-cx)/a)**2 + ((y-cy)/b)**2 > 1:
                      continue
                  if not self.traversable_grid[y,x]:
                      continue
                  if sun_avg[y,x] < sun_threshold:
                      continue

                  start = (y,x)
                  waypoints.append(start)
                  min_lander_dist_px = 0
                  break
              else:
                  print('Could not find viable start. Restarting waypoint selection...')
                  continue # restart outer loop
            else:
              # choose start
              waypoints.append(start)
              min_lander_dist_px = 0

            # choose waypoints progressively farther from start
            for i in range(max_attempts):
                while_counter = 0
                min_lander_dist_px = dist(start, waypoints[-1]) if len(waypoints) > 1 else 0
                while len(waypoints) < stop_locations:
                    # prevent infinite loop
                    while_counter += 1
                    if while_counter >= 500:
                      # print('Could not find viable random waypoints based on chosen start location. Restarting waypoint selection...')
                      if PRESET_START == False: # choose new start
                        for i in range(attempts):
                            x = np.random.randint(cx-a, cx+a)
                            y = np.random.randint(cy-b, cy+b)

                            if ((x-cx)/a)**2 + ((y-cy)/b)**2 > 1:
                                continue
                            if not self.traversable_grid[y,x]:
                                continue
                            if sun_avg[y,x] < sun_threshold:
                                continue

                            start = (y,x)
                            waypoints[0] = start
                            min_lander_dist_px = 0
                            break
                        else:
                          waypoints = waypoints[:1]
                      break

                    x = np.random.randint(cx-a, cx+a)
                    y = np.random.randint(cy-b, cy+b)
                    current_point = (y,x)

                    if not self.traversable_grid[y,x]:
                        continue
                    if sun_avg[y,x] < sun_threshold:
                        continue
                    if not line_of_sight(self.elevation, start, current_point):
                        continue

                    # check if waypoints are a min distance away from each other
                    dist_from_last = dist(waypoints[-1], current_point)
                    if dist_from_last < min_sep_px:
                        continue
                    if dist_from_last > max_sep_px:
                        continue

                    # ensure radial distance from lander increases w each waypoint
                    dist_from_lander = dist(start, current_point)
                    if dist_from_lander <= min_lander_dist_px:
                        continue

                    min_lander_dist_px = dist_from_lander

                    waypoints.append(current_point)

                    if len(waypoints) == stop_locations:
                        return waypoints

        if len(waypoints) < stop_locations:
            print('Failed to find viable waypoints.')

        return None

    ######## WAYPOINT SELECTION FUNCTION WITH PRE-SELECTED START
    def choose_waypoints_monte_carlo(self, distance_range_m, elevation, sun_avg, mission_site, start):

        def dist(a, b):
            return np.sqrt((a[0]-b[0])**2 + (a[1]-b[1])**2)

        cx, cy, __, __ = mission_site
        a = int((self.major_axis * 1000)/10)//2
        b = int((self.minor_axis * 1000)/10)//2

        min_sep_px = int(distance_range_m[0]/10)
        max_sep_px = int(distance_range_m[1]/10)

        sun_threshold = 50 # percent
        stop_locations = 3 # number of payloads / drop-off locations

        max_attempts = 20
        attempts = 500

        for __ in range(max_attempts): # overall waypoint selection loop
            while_counter = 0
            waypoints = []
            last_dist = 0

            # choose start
            waypoints.append(start)
            min_lander_dist_px = 0

            # choose waypoints progressively farther from start
            for i in range(max_attempts):
                while_counter = 0
                while len(waypoints) < stop_locations:
                    # prevent infinite loop
                    while_counter += 1
                    if while_counter >= 500:
                        # print('Could not find viable random waypoints based on chosen start location. Restarting waypoint selection...')
                        break

                    x = np.random.randint(cx-a, cx+a)
                    y = np.random.randint(cy-b, cy+b)
                    current_point = (y,x)

                    if not self.traversable_grid[y,x]:
                        continue
                    if sun_avg[y,x] < sun_threshold:
                        continue
                    if not line_of_sight(elevation, start, current_point):
                        continue

                    # check if waypoints are a min distance away from each other
                    dist_from_last = dist(waypoints[-1], current_point)
                    if dist_from_last < min_sep_px:
                        continue
                    if dist_from_last > max_sep_px:
                        continue

                    # ensure radial distance from lander increases w each waypoint
                    dist_from_lander = dist(start, current_point)
                    if dist_from_lander <= min_lander_dist_px:
                        continue

                    min_lander_dist_px = dist_from_lander

                    waypoints.append(current_point)

                    if len(waypoints) == stop_locations:
                        return waypoints

        if len(waypoints) < stop_locations:
            print('Failed to find viable waypoints.')

        return None

    """
    -----Reference Frames----
    Pixel Coordinates: (row, col) -- with origin at top left, this system denotes grid indices, with each pixel representing 10 m.
    Projected Coordinates: (x, y)-- with origin at South pole, this system denotes Cartesian distance of waypoint from south pole in meters.
    Local Frame: (dx, dy) -- with origin at the first waypoint (the lander), this system denotes Cartesian distance of waypoint from lander in meters.
    Polar: (r, theta) -- with origin at the first waypoint (the lander), this system denotes radial distance of waypoint from lander in meters, then heading of rover with theta.
    Latitude Longitude: (lat, lon) -- moon-based latitude longitude system

    """
    def print_waypoints(self, waypoints, elevation_file, transform):
        with rasterio.open(elevation_file) as src:
            # transformer: projection -> Moon lat/lon
            transformer = Transformer.from_crs(src.crs, src.crs.geodetic_crs, always_xy=True)

            # default origin = first waypoint
            origin_pix = waypoints[0]

            # origin in projected meters
            x0, y0 = transform*(origin_pix[1], origin_pix[0])

            print("\n--- WAYPOINTS (ALL COORDINATE SYSTEMS) ---\n")

            for i, (row, col) in enumerate(waypoints):
                # pixel coords
                pixel_coords = f"(row={row}, col={col})"

                # projected coordinates
                x, y = transform*(col, row)

                # relative to lander
                dx = x - x0
                dy = y - y0

                # polar coords
                r = np.sqrt(dx**2 + dy**2)
                theta = np.degrees(np.arctan2(dy, dx))

                # latitude and longitude
                lon, lat = transformer.transform(x, y)

                print(f"Waypoint {i+1}:")
                print(f"Pixel:              {pixel_coords}")
                print(f"Projected (m):      x={x:.2f}, y={y:.2f}")
                print(f"Local frame (m):    dx={dx:.2f}, dy={dy:.2f}")
                print(f"Polar:              r={r:.2f} m, θ={theta:.2f}°")
                print(f"Lat/Lon (Moon):     lat={lat:.6f}, lon={lon:.6f}")
                print()

class AnalyzePlotPaths:
    def __init__(self, world, full_path, transform):
        self.world = world
        self.full_path = full_path
        if full_path:
            self.axis_limits = self.calc_axis_limits(full_path)
        self.transform = transform

    def calc_axis_limits(self, full_path):
        full_path = np.array(full_path)

        y = full_path[:,0]
        x = full_path[:,1]

        buffer = 15

        x_min = int(x.min() - buffer)
        x_max = int(x.max() + buffer)
        y_min = int(y.min() - buffer)
        y_max = int(y.max() + buffer)

        # make sure limits are not negative
        x_min = max(0, x_min)
        y_min = max(0, y_min)

        return x_min, x_max, y_min, y_max

    def px_to_km(self, row, col):
        x_m, y_m = self.transform*(col, row)
        return x_m / 1000, y_m / 1000

    def px_limits_to_km(self):
        x_min, x_max, y_min, y_max = self.axis_limits
        x_min_km = self.px_to_km(y_min, x_min)[0]
        x_max_km = self.px_to_km(y_max, x_max)[0]
        y_min_km = self.px_to_km(y_max, x_min)[1]
        y_max_km = self.px_to_km(y_min, x_max)[1]
        return x_min_km, x_max_km, y_min_km, y_max_km

    def plot_path_on_hillshade(self, filename, full_path, waypoints, region_size):
        # open hillshade raster
        with rasterio.open(filename) as src:
            window = from_bounds(-region_size, -region_size, region_size, region_size, src.transform)
            hillshade = src.read(1, window = window)
            bounds = src.bounds

        h, w = hillshade.shape[:2]
        x_min_m, y_max_m = self.transform*(0, 0)
        x_max_m, y_min_m = self.transform*(w, h)
        extent = [x_min_m/1000, x_max_m/1000, y_min_m/1000, y_max_m/1000]

        # create figure
        fig, ax = plt.subplots(figsize=(8, 4))

        # plot hillshade
        ax.imshow(hillshade, cmap='gray', extent=extent)
        ax.grid(True, linestyle='--', alpha=0.5)

        # convert path to x, y
        full_path = np.array(full_path)
        xs_km = [self.px_to_km(r, c)[0] for r, c in full_path]
        ys_km = [self.px_to_km(r, c)[1] for r, c in full_path]

        # overlay D* path
        ax.plot(xs_km, ys_km, color='blue', linewidth=2, label='D* Path')

        # plot waypoints and path
        for i, (y, x) in enumerate(waypoints):
            x_km, y_km = self.px_to_km(y, x)
            if i == 0:
                ax.scatter(x_km, y_km, color='green', s=75, label='Start')
            elif i == len(waypoints) - 1:
                ax.scatter(x_km, y_km, color='red', s=75, label='Goal')
            else:
                ax.scatter(x_km, y_km, color='yellow', s=75)
            if i == 3 or i == 4 or i == 5:
                ax.text(x_km - 0.1, y_km - 0.1, f"WP{i+1}", color='black', fontsize=12)
            else:
                ax.text(x_km + 0.02, y_km + 0.02, f"WP{i+1}", color='black', fontsize=12)

        # --- Formatting ---
        ax.set_title("D* Path Over Lunar Hillshade")
        ax.set_xlabel("X (kilometers from lunar south pole)")
        ax.set_ylabel("Y (kilometers from lunar south pole)")
        ax.set_aspect('equal')
        ax.legend()

        x_min_lim, x_max_lim, y_min_lim, y_max_lim = self.px_limits_to_km()
        ax.set_xlim(x_min_lim, x_max_lim)
        ax.set_ylim(y_min_lim, y_max_lim)

        plt.tight_layout()
        plt.show()

    def plot_traversal_traversable(self, world, full_path, waypoints):
        size = world.grid.shape[0]
        img = np.zeros((size, size, 3))

        img[world.grid] = [1,1,1] # white = traversable
        img[~world.grid] = [0,0,0] # black = obstacles, not part of world.grid

        for y,x in full_path:
            img[y-1:y+1, x-1:x+1] = [0,0,1] # thicker path

        __, ax = plt.subplots(figsize=(10, 10))

        ax.grid(True, linestyle='--', alpha=0.5)
        h, w = world.grid.shape[:2]
        x_min_m, y_max_m = self.transform*(0, 0)
        x_max_m, y_min_m = self.transform*(w, h)
        extent = [x_min_m/1000, x_max_m/1000, y_min_m/1000, y_max_m/1000]

        ax.imshow(img, extent=extent)

        # show start and end point
        y0, x0 = waypoints[0]
        x0_km, y0_km = self.px_to_km(y0, x0)
        circle = plt.Circle((x0_km, y0_km), radius=0.05, color='green', fill=True)
        ax.add_patch(circle)
        ax.text(x0_km - 0.05, y0_km - 0.05, f"Start", color='green', fontsize=14)

        yf, xf = waypoints[-1]
        xf_km, yf_km = self.px_to_km(yf, xf)
        circle = plt.Circle((xf_km, yf_km), radius=0.05, color='red', fill=True)
        ax.add_patch(circle)
        ax.text(xf_km - 0.05, yf_km - 0.05, f"End", color='red', fontsize=14)

        total_distance = calculate_path_distance(full_path)

        legend = [
        matplotlib.patches.Patch(facecolor='white', edgecolor='black', linewidth=1.5, label='Traversable'),
        matplotlib.patches.Patch(facecolor='black', edgecolor='black', linewidth=1.5, label='Non-Traversable')]

        ax.set_title(f"Lunar Rover Traverse (D*) - {int(total_distance)} m Path")
        ax.legend(handles=legend, loc='upper right')
        ax.set_xlabel("X (kilometers from lunar south pole)")
        ax.set_ylabel("Y (kilometers from lunar south pole)")
        x_min_lim, x_max_lim, y_min_lim, y_max_lim = self.px_limits_to_km()
        ax.set_xlim(x_min_lim, x_max_lim)
        ax.set_ylim(y_min_lim, y_max_lim)
        plt.show()


    def plot_LOS_path(self, elevation, full_path, waypoints):
        x_min, x_max, y_min, y_max = self.axis_limits
        __, ax = plt.subplots(figsize=(8, 4))

        # base layer - elevation heatmap
        local_elevation = elevation[y_min:y_max, x_min:x_max]
        vmin = np.min(local_elevation)
        vmax = np.max(local_elevation)

        ax.grid(True, linestyle='--', alpha=0.5)
        h, w = elevation.shape[:2]
        x_min_m, y_max_m = self.transform*(0, 0)
        x_max_m, y_min_m = self.transform*(w, h)
        extent = [x_min_m/1000, x_max_m/1000, y_min_m/1000, y_max_m/1000]

        im = ax.imshow(elevation, cmap='terrain', vmin=vmin, vmax=vmax, extent=extent)

        cbar = plt.colorbar(im, ax=ax)
        cbar.set_label("Lunar Elevation (m)")

        # draw path and check LOS between point and lander
        for i in range(len(full_path) - 1):
            p1 = full_path[i]
            p2 = full_path[i+1]

            # check LOS between node and lander
            if line_of_sight(elevation, p1, waypoints[0]):
                color = 'green'
            else:
                color = 'black'

            x1_km, y1_km = self.px_to_km(p1[0], p1[1])
            x2_km, y2_km = self.px_to_km(p2[0], p2[1])
            ax.plot([x1_km, x2_km], [y1_km, y2_km], color=color, linewidth=2)

        # draw waypoints
        for i, wp in enumerate(waypoints):
            y, x = wp
            x_km, y_km = self.px_to_km(y, x)
            circle = plt.Circle((x_km, y_km), radius=0.05, color='blue', fill=True)
            ax.add_patch(circle)
            ax.text(x_km + 0.05, y_km + 0.05, f"WP{i+1}", color='blue', fontsize=12)

        ax.set_title("Line of Sight (LOS) on D* Path\nGreen = LOS, Black = No LOS")
        ax.set_xlabel("X (kilometers from lunar south pole)")
        ax.set_ylabel("Y (kilometers from lunar south pole)")
        ax.set_aspect('equal')
        x_min_lim, x_max_lim, y_min_lim, y_max_lim = self.px_limits_to_km()
        ax.set_xlim(x_min_lim, x_max_lim)
        ax.set_ylim(y_min_lim, y_max_lim)
        plt.show()

    """
    Calculates whether the rover is in sunlight or shade at the time t it is traversing a certain
    pixel on the pre-determined D* path. Based on the rover travelling 2 cm/s, or 10/0.02 = 200 seconds to traverse each pixel.
    """
    def plot_illumination_path(self, sun_data, avg_sun, full_path, waypoints):
        x_min, x_max, y_min, y_max = self.axis_limits

        fig, ax = plt.subplots(figsize=(8, 4))

        # --- Base layer: solar illumination heatmap ---
        h, w = avg_sun.shape[:2]
        x_min_m, y_max_m = self.transform*(0, 0)
        x_max_m, y_min_m = self.transform*(w, h)
        extent = [x_min_m/1000, x_max_m/1000, y_min_m/1000, y_max_m/1000]

        im = ax.imshow(avg_sun, cmap='inferno', extent=extent)

        cbar = plt.colorbar(im, ax=ax)
        cbar.set_label("Average Sunlight (%)")

        ax.grid(True, linestyle='--', alpha=0.5)

        rover_speed = 0.02  # m/s
        meters_per_pixel = 10
        time_per_pixel = meters_per_pixel / rover_speed  # 500 sec per pixel
        sun_window_time = 10 * 3600  # 10 hours in seconds

        total_time = 0

        # --- Overlay path colored by sunlight at time t ---
        for i in range(len(full_path) - 1):
            p1 = full_path[i]
            p2 = full_path[i+1]

            total_time += time_per_pixel

            sun_idx = int(total_time / sun_window_time)
            sun_idx = min(sun_idx, sun_data.shape[2] - 1)

            y, x = p1

            if sun_data[y, x, sun_idx] >= 0.75:
                color = 'green'
            else:
                color = 'black'

            x1_km, y1_km = self.px_to_km(p1[0], p1[1])
            x2_km, y2_km = self.px_to_km(p2[0], p2[1])
            ax.plot([x1_km, x2_km], [y1_km, y2_km], color=color, linewidth=2)

        # --- Draw waypoints ---
        for i, wp in enumerate(waypoints):
            y, x = wp
            x_km, y_km = self.px_to_km(y, x)
            circle = plt.Circle((x_km, y_km), radius=0.05, color='blue', fill=True)
            ax.add_patch(circle)
            ax.text(x_km + 0.02, y_km + 0.02, f"WP{i+1}", color='blue', fontsize = 12)

        ax.set_xlabel("X (kilometers from lunar south pole)")
        ax.set_ylabel("Y (kilometers from lunar south pole)")
        ax.set_aspect('equal')
        x_min_lim, x_max_lim, y_min_lim, y_max_lim = self.px_limits_to_km()
        ax.set_xlim(x_min_lim, x_max_lim)
        ax.set_ylim(y_min_lim, y_max_lim)
        ax.set_title("D* Path Over Solar Illumination Map\nGreen = Sunlight, Black = Shadow")
        plt.show()

    def traversable_plot_slope_crop(self, traversable_grid, transform):
        world = TerrainWorld(traversable_grid)

        size = world.grid.shape[0]

        img = np.zeros((size, size, 3))
        h, w = img.shape[:2]

        img[world.grid] = [1,1,1] # white = traversable
        img[~world.grid] = [0,0,0] # black = obstacles, not part of world.grid

        legend = [
            matplotlib.patches.Patch(facecolor='white', edgecolor='black', linewidth=1.5, label='Traversable'),
            matplotlib.patches.Patch(facecolor='black', edgecolor='black', linewidth=1.5, label='Non-Traversable')]

        __, ax = plt.subplots(figsize=(10, 10))
        ax.imshow(img)
        ax.grid(True, linestyle='--', alpha=0.5)
        x_min, y_max = transform * (0, 0)
        x_max, y_min = transform * (w, h)

        fontsize = 16
        ax.imshow(img, extent=[x_min/1000, x_max/1000, y_min/1000, y_max/1000])

        ax.legend(handles=legend, loc='upper right',  fontsize=fontsize)
        ax.set_xlabel("X (km from lunar south pole)",  fontsize=fontsize)
        ax.set_ylabel("Y (km from lunar south pole)", fontsize=fontsize)
        ax.set_aspect('equal')
        ax.set_title(f"Traversable Regions Based on <10° Slope Requirement", fontsize=fontsize)
        # ax.axis('off')
        plt.show()

    def overall_monte_carlo_plot(self, all_results, n_sims, failures):
        def distance_vs_LOS(sims_distances, sims_percent_LOS, sims_longest_los):
            fig, ax = plt.subplots(figsize=(6, 6))
            threshold_m = 50
            colors = ['green' if v < threshold_m else 'red' for v in sims_longest_los]
            ax.scatter(sims_distances, [v*100 for v in sims_percent_LOS],
                    c=colors, edgecolors='white', linewidths=0.5, s=60)
            ax.set_xlabel('Total Path Distance (m)', fontsize=13)
            ax.set_ylabel('LOS Coverage (%)', fontsize=13)
            ax.set_title('LOS Coverage vs Path Distance', fontsize=14, fontweight='bold')
            ax.grid(True, linestyle='--', alpha=0.4)
            from matplotlib.lines import Line2D
            ax.legend(handles=[
                Line2D([0],[0], marker='o', color='w', markerfacecolor='green',  markersize=9, label=f'Longest LOS blackout < {threshold_m} m'),
                Line2D([0],[0], marker='o', color='w', markerfacecolor='red', markersize=9, label=f'Longest LOS blackout ≥ {threshold_m} m'),
            ], fontsize=10)
            plt.tight_layout()
            plt.show()
        def distance2_vs_LOS(sims_distances, sims_percent_LOS, sims_longest_los):
            fig, ax = plt.subplots(figsize=(6, 6))
            # threshold_m = 50
            # colors = ['green' if v < threshold_m else 'red' for v in sims_longest_los]
            ax.scatter(sims_distances, [v*100 for v in sims_percent_LOS],
                    c='green', edgecolors='white', linewidths=0.5, s=60)
            ax.set_xlabel('Total Path Distance (m)', fontsize=13)
            ax.set_ylabel('LOS Coverage (%)', fontsize=13)
            ax.set_title('LOS Coverage vs Path Distance', fontsize=14, fontweight='bold')
            ax.grid(True, linestyle='--', alpha=0.4)
            from matplotlib.lines import Line2D
            # ax.legend(handles=[
            #     Line2D([0],[0], marker='o', color='w', markerfacecolor='green',  markersize=9, label=f'Longest blackout < {threshold_m} m'),
            #     Line2D([0],[0], marker='o', color='w', markerfacecolor='red', markersize=9, label=f'Longest blackout ≥ {threshold_m} m'),
            # ], fontsize=10)
            plt.tight_layout()
            plt.show()
        def distance_vs_sun(sims_distances, sims_percent_sun):
            fig, ax = plt.subplots(figsize=(6, 6))
            plt.scatter(sims_distances, sims_percent_sun)
            plt.xlabel('Total Distance Traveled (m)')
            plt.ylabel('Percent Sun Cover (%)')
            ax.set_title(f"Sun Cover Percent for Total Mission Distance Traveled", fontsize=16)
            plt.show()
        def LOS_sun_cover(sims_percent_sun, sims_percent_LOS):
            fig, ax = plt.subplots(figsize=(6, 6))
            plt.scatter(sims_percent_sun, sims_percent_LOS)
            plt.xlabel('Percent Sun Cover (%)')
            plt.ylabel('Percent LOS (%)')
            ax.set_title(f"Monte Carlo Runs", fontsize=16)
            ax.legend(fontsize=10)
            ax.grid(True, linestyle='--', alpha=0.4)
            plt.tight_layout()
            plt.show()
        def success_vs_landing_uncertainty(sims_landing_err, sims_percent_LOS, sims_percent_sun, sims_longest_los, sun_req=75):
            fig, ax1 = plt.subplots(figsize=(6, 6))
            from matplotlib.lines import Line2D

            los_pct = [v*100 for v in sims_percent_LOS]
            # sun_pct = [v*100 for v in sims_percent_sun]

            # left: landing error vs LOS
            threshold_m = 50
            colors = ['green' if v < threshold_m else 'red' for v in sims_longest_los]
            ax1.scatter(sims_landing_err, los_pct, c=colors,
                        edgecolors='white', linewidths=0.5, s=60)
            ax1.set_xlabel('Landing Error (m)', fontsize=12)
            ax1.set_ylabel('LOS Coverage (%)', fontsize=12)
            ax1.set_ylim(0, 105)
            ax1.set_title('Landing Error vs LOS Coverage', fontsize=13, fontweight='bold')
            ax1.legend(fontsize=10)
            ax1.grid(True, linestyle='--', alpha=0.4)
            ax1.legend(handles=[
                Line2D([0],[0], marker='o', color='w', markerfacecolor='green',  markersize=9, label=f'Longest blackout < {threshold_m} m'),
                Line2D([0],[0], marker='o', color='w', markerfacecolor='red', markersize=9, label=f'Longest blackout ≥ {threshold_m} m'),
            ], fontsize=10)

            # # right: landing error vs sun
            # colors_sun = ['green' if v >= sun_req else 'red' for v in sun_pct]
            # ax2.scatter(sims_landing_err, sun_pct, c=colors_sun,
            #             edgecolors='white', linewidths=0.5, s=60)
            # ax2.axhline(sun_req, color='darkorange', linewidth=1.8, linestyle='--',
            #             label=f'Sun requirement: {sun_req}%')
            # ax2.set_xlabel('Landing Error (m)', fontsize=12)
            # ax2.set_ylabel('Sun Coverage (%)', fontsize=12)
            # ax2.set_ylim(0, 105)
            # ax2.set_title('Landing Error vs Sun Coverage', fontsize=13, fontweight='bold')
            # ax2.legend(fontsize=10)
            # ax2.grid(True, linestyle='--', alpha=0.4)

            plt.suptitle('Impact of Landing Uncertainty on Mission Coverage', fontsize=14, fontweight='bold', y=1.02)
            plt.tight_layout()
            plt.show()

        sims_distances = []
        sims_percent_LOS = []
        sims_percent_sun = []
        sims_landing_err = []
        sims_total_dist = []
        sims_longest_los = []
        sims_longest_sun = []
        sims_mission_site = []
        for sim in all_results:
            sims_distances.append(sim["Distance"])
            sims_percent_LOS.append(sim["Percent_LOS"])
            sims_percent_sun.append(sim["Sun_fraction"])
            sims_landing_err.append(sim["landing_error_m"])
            sims_total_dist.append(sim["Distance"])
            sims_longest_los.append(sim["longest_los_m"])
            sims_longest_sun.append(sim["longest_sun_loss_m"])
            sims_mission_site.append(sim["Mission_Site"])

        failures = n_sims - len(all_results)

        LOS_sun_cover(sims_percent_sun, sims_percent_LOS)
        distance_vs_LOS(sims_distances, sims_percent_LOS, sims_longest_los)
        distance_vs_sun(sims_distances, sims_percent_sun)
        success_vs_landing_uncertainty(sims_landing_err, sims_percent_LOS, sims_percent_sun, sims_longest_los)
        # site_success_breakdown(all_results, sims_longest_los)

        # print averages
        avg_total_distance = np.mean(sims_total_dist)
        avg_LOS = np.mean(sims_percent_LOS)
        avg_sun = np.mean(sims_percent_sun)


        success = 0
        # count num success based upon LOS
        for i in range(len(sims_longest_los)):
            if sims_longest_los[i] <= 50:
                success +=1

        print('\nAverage Metrics\n')
        print(f'Number of Successful Runs out of Total {n_sims} Runs: {success} runs')
        print(f'Average total distance: {avg_total_distance} m')
        print(f'Average LOS: {avg_LOS*100}%')
        print(f'Average sun cover: {avg_sun*100}%')
        print(f'Minimum path distance: {np.min(sims_total_dist)}')
        print(f'Maximum path distance: {np.max(sims_total_dist)}')
        print(f'Average LOS loss: {np.mean(sims_longest_los)} m')


    def read_path_results(self):
        csv_file_path = "planned_path_nodes_70.0.csv"

        with open(csv_file_path, mode='r') as file:
            reader = csv.reader(file)
            full_path_x = []
            full_path_y = []

            # skip first two lines
            next(reader)

            # read each waypoint
            for row in reader:
                full_path_x.append(float(row[0]))
                full_path_y.append(float(row[1]))

        print(f"The path has been read successfully inside '{csv_file_path}'.")

        full_path = np.array([full_path_x, full_path_y]).T
        return full_path

def store_path_results(full_path, waypoints, format):
    total_distance = calculate_path_distance(full_path)

    csv_file_path = f"Dstar_path_{int(total_distance)}_METERS.csv"

    if format == "METERS":
        csv_file_path = f"Dstar_path_{int(total_distance)}_METERS.csv"
        scale = 10
    elif format == "PIXELS":
        csv_file_path = f"Dstar_path_{int(total_distance)}_PIXELS.csv"
        scale = 1
    else:
        print('csv file name format not recognized. Proceeding to write file in pixels...')
        csv_file_path = f"Dstar_path_{int(total_distance)}_PIXELS.csv"
        scale = 1

    with open(csv_file_path, mode='w', newline='') as file:
        writer = csv.writer(file)

        # write header
        writer.writerow(["x", "y"])

        # write each part of path
        for node in full_path:
            writer.writerow([node[1]*scale, node[0]*scale])

    print(f'Total distance traversed: {total_distance} m')
    print(f"The path has been stored successfully inside '{csv_file_path}'.")

def calculate_path_distance(full_path):
    total_distance = 0

    for i in range(len(full_path) - 1):
        dx = abs(full_path[i+1][0] - full_path[i][0])
        dy = abs(full_path[i+1][1] - full_path[i][1])

        if dx == 1 and dy == 1: # diagonal movement
            total_distance += 10*math.sqrt(2)
        elif dx == 1 and dy == 0: # straight movement
            total_distance += 10
        elif dx == 0 and dy == 1: # straight movement
            total_distance += 10
        elif dx == 0 and dy == 0: # repeated node
            total_distance += 0

    return total_distance

def distance_between_waypoints(full_path, waypoints):
    total_distance = 0

    j = 0
    for i in range(len(full_path) - 1):
        dx = abs(full_path[i+1][0] - full_path[i][0])
        dy = abs(full_path[i+1][1] - full_path[i][1])

        if dx == 1 and dy == 1: # diagonal movement
            total_distance += 10*math.sqrt(2)
        elif dx == 1 and dy == 0: # straight movement
            total_distance += 10
        elif dx == 0 and dy == 1: # straight movement
            total_distance += 10
        elif dx == 0 and dy == 0: # repeated node
            total_distance += 0

        # output current total distance if currently at a waypoint
        if j <= len(waypoints):
            if full_path[i][0] == waypoints[j][0] and full_path[i][1] == waypoints[j][1]:
                # print('check that the following are equal: ')
                # print(f'row: {full_path[i][0]} == {waypoints[j][0]}\ncol: {full_path[i][1]} == {waypoints[j][1]}')
                print(f'=== Waypoint {j+1} ===')
                print(f'Current total distance: {total_distance} m')
                j +=1
    if full_path[-1][0] == waypoints[j][0] and full_path[-1][1] == waypoints[j][1]:
        print(f'=== Waypoint {j+1} ===')
        print(f'Current total distance: {total_distance} m')

    return total_distance

def traversable_plot_slope(traversable_grid, transform):
      world = TerrainWorld(traversable_grid)

      size = world.grid.shape[0]

      img = np.zeros((size, size, 3))
      h, w = img.shape[:2]

      img[world.grid] = [1,1,1] # white = traversable
      img[~world.grid] = [0,0,0] # black = obstacles, not part of world.grid

      legend = [
          matplotlib.patches.Patch(facecolor='white', edgecolor='black', linewidth=1.5, label='Traversable'),
          matplotlib.patches.Patch(facecolor='black', edgecolor='black', linewidth=1.5, label='Non-Traversable')]

      __, ax = plt.subplots(figsize=(10, 10))
      ax.imshow(img)
      ax.grid(True, linestyle='--', alpha=0.5)
      x_min, y_max = transform * (0, 0)
      x_max, y_min = transform * (w, h)

      fontsize = 16
      ax.imshow(img, extent=[x_min/1000, x_max/1000, y_min/1000, y_max/1000])

      ax.legend(handles=legend, loc='upper right',  fontsize=fontsize)
      ax.set_xlabel("X (km from lunar south pole)",  fontsize=fontsize)
      ax.set_ylabel("Y (km from lunar south pole)", fontsize=fontsize)
      ax.set_aspect('equal')
      ax.set_title(f"Traversable Regions Based on <10° Slope Requirement", fontsize=fontsize)
      # ax.axis('off')
      plt.show()

def compute_metrics(full_path, waypoints, elevation, sun_data):
      total_distance = calculate_path_distance(full_path)

      # straight line distance
      straight_distance = np.linalg.norm(np.array(waypoints[-1]) - np.array(waypoints[0])) * 10  # pixels to meters

      # LOS / communication fraction
      los_count = sum(line_of_sight(elevation, node, waypoints[0]) for node in full_path)
      comm_fraction = los_count / len(full_path)

      # max radial distance from lander
      max_radial_dist = max(np.linalg.norm(np.array(node) - np.array(waypoints[0])) * 10 for node in full_path)

      # longest loss of LOS segment
      max_loss_streak = 0
      current_loss_streak = 0
      for node in full_path:
          if not line_of_sight(elevation, node, waypoints[0]):
              current_loss_streak += 1
              max_loss_streak = max(max_loss_streak, current_loss_streak)
          else:
              current_loss_streak = 0
      longest_los_loss_m = max_loss_streak * 10

      # longest loss of sunlight
      # longest continuous loss of sunlight
      max_sun_loss_streak = 0
      current_sun_loss_streak = 0
      total_time = 0
      sun_window_time = 10 * 3600
      rover_speed = 0.02
      meters_per_pixel = 10
      time_per_pixel = meters_per_pixel / rover_speed
      total_time = 0
      sun_count = 0

      for y, x in full_path:
          sun_idx = min(int(total_time / sun_window_time), sun_data.shape[2] - 1)
          if sun_data[y, x, sun_idx] < 0.9:
              current_sun_loss_streak += 1
              max_sun_loss_streak = max(max_sun_loss_streak, current_sun_loss_streak)
          else:
              current_sun_loss_streak = 0
          total_time += time_per_pixel

      longest_sun_loss_m = max_sun_loss_streak * 10

      # elevation range
      elevations = [elevation[y, x] for y, x in full_path]
      elevation_range_m = max(elevations) - min(elevations)

      # use time-resolved data like in plot_illumination_path
      rover_speed = 0.02
      meters_per_pixel = 10
      time_per_pixel = meters_per_pixel / rover_speed
      sun_window_time = 10 * 3600
      total_time = 0
      sun_count = 0

      for y, x in full_path:
          sun_idx = min(int(total_time / sun_window_time), sun_data.shape[2] - 1)
          if sun_data[y, x, sun_idx] >= 0.9:
              sun_count += 1
          total_time += time_per_pixel

      sun_fraction = sun_count / len(full_path)

      np.set_printoptions(precision=3)
      print(f"====Simulation Results =====")
      print(f"Waypoints: {waypoints}")
      print(f"Distance Traveled: {total_distance} m")
      print(f"Ending Distance from Lander: {straight_distance} m")
      print(f'Maximum Radial Distance: {max_radial_dist} m')
      print(f'Percent sun on path: {sun_fraction*100}%')
      print(f"Percent LOS on path: {comm_fraction*100}%")
      print(f'Longest LOS loss m: {longest_los_loss_m} m')
      print(f'Longest sun loss: {longest_sun_loss_m} m')
      print(f'Elevation range: {elevation_range_m} m')

      return total_distance, comm_fraction, straight_distance, max_radial_dist, sun_fraction, longest_los_loss_m, elevation_range_m, longest_sun_loss_m

def singular_run():
    # 1. USER INPUTS

    region_size = 25000 # meters -- specifies how large of a region to look at when determining mission site
    major_axis = 1 # km
    minor_axis = 1 # km
    distance_range_m = [50, 1000] # [min, max] in meters
    stop_locations = 3

    USE_PRESET_WAYPOINTS = False # change to TRUE if user wants to use custom waypoints
    USE_PRESET_MISSION_REGION = True
    start = False

    # 2. PRE-SET WAYPOINTS IF DESIRED
    # PRESET_WAYPOINTS = [(844, 4342), (825, 4375), (755, 4297)] # FINALLLLLLL
    PRESET_WAYPOINTS = [(844, 4342), (825, 4375), (755, 4297), (785,4275), (850, 4302), (833, 4425)]

    # load data and generate traversable grid
    elevation, slopes, sun_data, avg_sun, transform = load_data(ELEV_FILE, SLOPE_FILE, region_size)
    traversable_grid = traversability(elevation, slopes, avg_sun)

    # 3. WAYPOINT SELECTION
    if USE_PRESET_WAYPOINTS:
        waypoints = PRESET_WAYPOINTS
        # update mission site center to pre-set lander / start location
        mission_site = [PRESET_WAYPOINTS[0][0], PRESET_WAYPOINTS[0][1], 1, 1] # (cx, cy, trav, flatness)

    else:
        wp_generator = GenerateWaypoints(major_axis, minor_axis, traversable_grid, elevation)
        viable_sites = wp_generator.find_landing_ellipses()
        mission_site = viable_sites[np.random.randint(0,5)] # choose one of top five landing sites
        waypoints = wp_generator.choose_waypoints(avg_sun, distance_range_m, mission_site, start, stop_locations)

        # check for valid path between each set of waypoints

        # add binary LOS map to traversable grid
        start = waypoints[0]
        goal = waypoints[-1]

        los_map = wp_generator.precompute_los_map_downsampled(elevation, start, mission_site, major_axis, minor_axis, downsample=5)
        traversable_grid = traversable_grid & los_map

        world = TerrainWorld(traversable_grid)

        connected = False

    for attempt in range(5):
        connected = True  # assume valid until proven otherwise
        for i in range(len(waypoints) - 1):
            if not path_exists(world, waypoints[i], waypoints[i+1]):
                print("No valid rover path between start and goal. Choosing new waypoints...")
                connected = False
                break
        if connected:
            break  # there is a possible path
        # regenerate waypoints if failed
        waypoints = wp_generator.choose_waypoints(avg_sun, distance_range_m, mission_site, start, stop_locations)

    # 4. D* GLOBAL PATH PLANNING
    start = waypoints[0]
    goal = waypoints[-1]

    full_path = []
    current_start = start

    wp_generator = GenerateWaypoints(major_axis, minor_axis, traversable_grid, elevation)
    wp_generator.print_waypoints(waypoints, ELEV_FILE, transform)

    print('Planning path based on D star algorithm...')

    world = TerrainWorld(traversable_grid)
    size = traversable_grid.shape[0]

    for wp in waypoints[1:]:
        planner = DStarLite(size, current_start, wp, start, elevation, avg_sun)
        planner.compute_shortest_path(world)

        segment = extract_path(planner, world, current_start, wp)

        if segment is not None:
            if full_path:
                full_path.extend(segment[1:])
            else:
                full_path.extend(segment)
            current_start = wp

    if full_path:
        # distance_between_waypoints(full_path, waypoints) # for caleb's stopping code

        plotter = AnalyzePlotPaths(world, full_path, transform)
        plotter.traversable_plot_slope_crop(traversable_grid, transform) # plot travserability grid
        plotter.plot_path_on_hillshade("/content/drive/MyDrive/capstone_files/data/LDEM_83S_10MPP_ADJ_HILL.tiff", full_path, waypoints, region_size)
        plotter.plot_traversal_traversable(world, full_path, waypoints)
        plotter.plot_LOS_path(elevation, full_path, waypoints)
        plotter.plot_illumination_path(sun_data, avg_sun, full_path, waypoints)

        store_path_results(full_path, waypoints, format = "METERS")

        compute_metrics(full_path, waypoints, elevation, sun_data)
    else:
        print('No valid path found. Exiting.')


def multiple_runs(n_sims, landing_sigma_m):
    def landing_site_error(mission_site, landing_sigma_m, traversable_grid):
        # introduce Gaussian error in landing site
        cx, cy, trav_percent, elev_std = mission_site
        landing_sigma_px = landing_sigma_m / 10  # convert from meters to pixels
        for _ in range(100):  # try until we land on traversable terrain
            new_cx = int(np.random.normal(cx, landing_sigma_px))
            new_cy = int(np.random.normal(cy, landing_sigma_px))
            new_cx = np.clip(new_cx, 0, traversable_grid.shape[1]-1)
            new_cy = np.clip(new_cy, 0, traversable_grid.shape[0]-1)

            if traversable_grid[new_cy, new_cx]:
                break

        actual_lander = (new_cy, new_cx)  # this IS the lander position
        new_mission_site = (new_cx, new_cy, trav_percent, elev_std)
        return new_mission_site, actual_lander

    results = []
    failures = {"no_waypoints": 0, "no_path": 0, "planner_timeout": 0}

    # 1. USER INPUTS
    region_size = 25000 # meters
    major_axis = 1.1 # km
    minor_axis = 1.1
    distance_range_m = [50, 1000]
    stop_locations = 3

    # 2. PRE-SET SAVED LANDER LOCATION IF DESIRED
    PRESET_MISSION_REGION = True # use ORIGINAL_START as the goal lander location and determine center of mission site
    ORIGINAL_START = (18500, 16500) # meters from true South
    CONSTANT_WAYPOINTS = False # attempt to reach same waypoints CONSTANT mission region every time

    # original_start = (16010, 17800)

    # 3. LOAD DATA AND GENERATE TRAVERSABILITY GRID
    elevation, slopes, sun_data, avg_sun, transform = load_data(ELEV_FILE, SLOPE_FILE, region_size)
    traversable_grid = traversability(elevation, slopes, avg_sun)
    wp_generator = GenerateWaypoints(major_axis, minor_axis, traversable_grid, elevation)

    # 4. SET MISSION SITE BY EITHER ITERATING THROUGH REGIONS OR USING USER-INPUT FOR LANDER LOCATION
    if not PRESET_MISSION_REGION:
        viable_sites = wp_generator.find_landing_ellipses()
        mission_site_original = viable_sites[np.random.randint(0,5)] # choose one of top three landing sites
    else:
        viable_sites = []
        # convert original_start from meters to pixel (row, col)
        inv_transform = ~transform
        col, row = inv_transform*ORIGINAL_START
        original_start_px = (int(row), int(col))
        mission_site_original = (original_start_px[1], original_start_px[0], 1, 10) # centered around start waypoint for now, the other two values aren't accurate so deleted them

    if CONSTANT_WAYPOINTS:
      preset_wps = wp_generator.choose_waypoints(avg_sun, distance_range_m, mission_site_original, original_start_px, stop_locations)

    # 5. LOOP THROUGH SIMULATION RUNS, CHANGING LANDING SITE ERROR AT EACH RUN
    for sim in range(n_sims):
        # 6. PRETURB LANDING SITE
        mission_site, start = landing_site_error(mission_site_original, landing_sigma_m, traversable_grid) # include Gaussian uncertainty for landing site

        # commented this out to help with algorithm convergence and computational efficiency
        los_map = wp_generator.precompute_los_map_downsampled(elevation, start, mission_site, major_axis, minor_axis, downsample=5)

        sim_grid = traversable_grid & los_map

        # 7. EITHER CHOOSE NEW WAYPOINTS BASED ON UPDATED LANDING REGION OR ATTEMPT TO FIND A PATH WITH OLD WAYPOINTS
        if not CONSTANT_WAYPOINTS:
          waypoints = wp_generator.choose_waypoints(avg_sun, distance_range_m, mission_site, start, stop_locations)
        else:
          waypoints = [start] + preset_wps[1:] # add pre set waypoints after starting location
          mission_site = mission_site_original

        if waypoints is None:
            print(f'Simulation {sim+1}: Failure to determine viable waypoints. Skipping to next sim iteration.')
            failures["no_waypoints"] += 1
            continue

        # start = waypoints[0]
        goal = waypoints[-1]

        world = TerrainWorld(sim_grid)
        size = sim_grid.shape[0]

        # 8. ENSURE ALL WAYPOINTS ARE CONNECTED
        connected = True
        if not CONSTANT_WAYPOINTS:
          connected = False
          for attempt in range(5):
              connected = True  # assume valid until proven otherwise
              for i in range(len(waypoints) - 1):
                  if not path_exists(world, waypoints[i], waypoints[i+1]):
                      print("No valid rover path between start and goal. Choosing new waypoints...")
                      connected = False
                      break
              if connected:
                  break  # there is a possible path
              # regenerate waypoints if failed
              waypoints = wp_generator.choose_waypoints(avg_sun, distance_range_m, mission_site, start, stop_locations)
              if waypoints is None:
                print(f'Simulation {sim+1}: Failure to determine viable waypoints. Skipping to next sim iteration.')
                failures["no_waypoints"] += 1
                continue

        if not connected:
            print(f"Simulation {sim+1}: no valid path, skipping.")
            failures["no_path"] += 1
            continue

        # 9. PLAN D* PATH ACROSS CONSECUTIVE WAYPOINTS
        full_path = []
        current_start = start

        for wp in waypoints[1:]:
            planner = DStarLite(size, current_start, wp, start, elevation, avg_sun)
            planner.compute_shortest_path(world)

            segment = extract_path(planner, world, current_start, wp)

            if segment is not None:
                if full_path:
                    full_path.extend(segment[1:])
                else:
                    full_path.extend(segment)
                current_start = wp

        total_distance = calculate_path_distance(full_path)
        if current_start != goal or total_distance == 0:
            print(f"Simulation {sim+1}: no valid path, skipping.")
            failures["no_path"] += 1
            continue

        # 10. OUTPUT SIM RUN RESULTS
        print(f"====Simulation {sim+1} Results =====")
        total_distance, comm_fraction, straight_distance, max_radial_dist, sun_fraction, longest_los_m, elevation_range_m, longest_sun_loss_m = compute_metrics(full_path, waypoints, elevation, sun_data)
        if CONSTANT_WAYPOINTS:
          land_error = np.linalg.norm(np.array(start[:2]) - np.array(original_start_px[:2])) * 10
        else:
          land_error = np.linalg.norm(np.array(mission_site_original[:2][::-1]) - np.array(mission_site[:2][::-1]))*10
        results.append({
            "Simulation": sim+1,
            "Mission_Site": mission_site,
            "Waypoints": waypoints,
            "Path": full_path,
            "Distance": total_distance, ###
            "Distance_from_lander": straight_distance,
            "Max_radial_distance": max_radial_dist,
            "Sun_fraction": sun_fraction, ###
            "Percent_LOS": comm_fraction, ###
            "landing_error_m": land_error, ##
            "longest_los_m":  longest_los_m, # loss
            "elevation_range_m": elevation_range_m,
            "longest_sun_loss_m": longest_sun_loss_m})
        print(f'Landing error: {land_error} m')

    print('\n=====OVERALL MONTE CARLO RESULTS=====\n')
    print(f'Region Size = {region_size} m --- Major Axis = {major_axis} m --- Minor Axis = {minor_axis}')
    success_rate = len(results) / n_sims
    print(f"\nSuccess rate: {success_rate*100:.1f}%")
    print(f"Failures: {failures}\n")

    best_sims = sorted(results, key=lambda x: x["Percent_LOS"], reverse=True)[:3]
    for sim in best_sims:
        print(f'\nSimulation #{sim["Simulation"]}')
        print(f"Percent LOS on path: {sim["Percent_LOS"]*100}")
        store_path_results(sim["Path"], sim["Waypoints"], format="METERS")
        store_path_results(sim["Path"], sim["Waypoints"], format="PIXELS")

    if results:
        plotter = AnalyzePlotPaths(world, full_path, transform)
        plotter.overall_monte_carlo_plot(results, n_sims, failures)



# singular_run()

multiple_runs(n_sims = 50, landing_sigma_m = 166.6) # changes mission region based on landing site

