clear; clc; close all;

%% USER PARAMETERS

battery_mass = 1.66;               % kg 
batt_specific_energy = 248.6;      % Wh/kg
E_batt_capacity = battery_mass * batt_specific_energy;

initial_SOC_fraction = 0.85;     % 85% charged at mission start assume charged in the last 7 - 30 days

speed = 0.02;                    % m/s
P_motors = 26;                   % W

P_IMU = 1.5;                     % W
P_UWB = 1.68;                    % W
P_sun_sensor = 0.0759;           % W
P_camera = 0.3135;               % W
P_lidar = 6.5;                   % W
lidar_use_fraction = 0.25;
P_comp = 9;                      % W
P_MCU = 0.072;                   % W
P_buck = 2*0.45;                 % W
P_driver = 4*0.8;                % W

P_heaters = 6.5;                 % W

P_av_travel = P_IMU + P_UWB + P_sun_sensor + P_lidar*lidar_use_fraction + P_comp + P_MCU + P_buck + P_driver;
P_av_rest = P_IMU + P_comp;

payload_total_power_n = 15;       % W
num_of_payloads = 2;

payload_drop_distances = [20000 20000];
payload_science_power = 30;       % W (while doing science use this wattage)
num_science_stops = 2;
science_stops_dist = [14, 576];     % meters  -- distance at which each stop occurs 
% If you want a stop at each of Sayali's way points use: 14, 576,1804, 2341, 4508, 6200
science_stop_times = [5, 5];         % hours  -- how long each stop lasts

charge_start_fraction = 0.20;
charge_stop_fraction  = 0.80;

% total distance is set automatically from the path after sun_map.mat loads

%% PANEL PROPERTIES

panel_number  = 4;
panel_widths  = [0.25, 0.25, 0.3, 0.3]; % front, back, side side
panel_height  = [0.37, 0.25, 0.37, 0.37];

lidar_cutout = 0.06*0.06;
motor_cutout = 0.07715*0.07215;
sun_sensor_cutout = 0.0463*0.0203;

obstructions = [lidar_cutout+sun_sensor_cutout, 0, 2*motor_cutout+sun_sensor_cutout, 2*motor_cutout+sun_sensor_cutout];

panel_eff   = 0.32;
inc_derate  = 0.95;

%% TIME + SOLAR CONSTANTS
% key parameter n: mission start Earth day
% match it to the n used in build_sun_map
n       = 2855;
day     = n - 2830;
Tau     = deg2rad(-1.545);
Y       = 346.71;
t_0     = -1.23;

T_total = 24*14;
% dt and N will be loaded from sun_map.mat below to guarantee sync

omega   = 360 / T_total;

%% MOON GEOMETRY
% for the curve correction

R_moon = 1737400;
L      = deg2rad(-90);
E      = deg2rad(90);

%% SOLAR CONSTANTS

G_sc = 1361;

%% LOAD SUN MAP
% sun_map(path_node, time_step) = 1 (sunlit) or 0 (shadow)
% Generated by build_sun_map.m from the planned path csv + DEM

load('sun_map.mat', 'sun_map', 'path_x_km', 'path_y_km', 'n_path', 'N', 'dt');
% N and dt are loaded from sun_map.mat so the time vector here is
% guaranteed to match the one used when sun_map was built.
% This prevents index-out-of-bounds errors if dt was changed between runs.
t       = 0:dt:T_total;
N_check = length(t);
if N_check ~= N
    warning('Time vector length mismatch: SOC=%d, sun_map=%d. Using sun_map N.', N_check, N);
    t = linspace(0, T_total, N);   % force exact match
end
fprintf('sun_map dt=%.4f hr, N=%d steps\n', dt, N);


% Build cumulative distance along path in meters.
% path_x_km / path_y_km are in km. convert to metres.
% This lets us map current_distance (m). nearest path node index.

path_x_m = path_x_km * 1000;
path_y_m = path_y_km * 1000;

seg_lengths  = sqrt(diff(path_x_m).^2 + diff(path_y_m).^2);
cum_dist_path = [0; cumsum(seg_lengths)];   % n_path x 1, metres
total_distance_goal = cum_dist_path(end);   % set from actual path length

fprintf('Path loaded: %d nodes, total length %.1f m\n', ...
    n_path, cum_dist_path(end));

%% PANEL GEOMETRY (precompute)

azi_p = linspace(0, 360, panel_number+1);
azi_p(end) = [];
azi_p = deg2rad(azi_p);

theta_dip = acos(R_moon / (R_moon + panel_height(1)));

%% MISSION STATE VARIABLES

SOC      = zeros(1, N);
SOC(1)   = initial_SOC_fraction * E_batt_capacity;

distance = zeros(1, N);

payloads_remaining = num_of_payloads;
next_payload_index = 1;

in_charging    = false;
mission_failed = false;   % permanent - rover cannot recover once SOC hits 0

in_science          = false;   % true while rover is stopped doing science
next_science_index  = 1;       % index into science_stops_dist / science_stop_times
science_time_elapsed = 0;      % hours spent at current science stop

% Tracking arrays for visualisation
illum_log    = zeros(1, N);   % I_illum at each timestep
charging_log = false(1, N);   % in_charging state at each timestep
P_solar_log  = zeros(1, N);   % actual solar power generated
science_log  = false(1, N);   % in_science state at each timestep

%% MAIN TIME LOOP

t_lunar_offset = (n - 2831) * 24;

for i = 2:N

    if mission_failed
        distance(i) = distance(i-1);
        SOC(i)      = 0;
        continue
    end

    current_distance = distance(i-1);

    
    % FIND CURRENT PATH NODE
    % Map current odometer distance to the closest node on the planned path.
    % The path is traversed in order
   
    [~, path_node] = min(abs(cum_dist_path - current_distance));
    path_node = max(1, min(n_path, path_node));


    % ILLUMINATION AT CURRENT POSITION + TIME
    % sun_map uses the same time index i as the main loop.

    I_illum = double(sun_map(path_node, i));   % 1 = sunlit, 0 = shadow


    % SOLAR POWER AT THIS TIMESTEP

    ti = t(i);

    delta = Tau * sin(deg2rad(360/Y * (n + ti/24 - t_0)));
    H     = deg2rad(omega * (T_total/2 - (ti + t_lunar_offset)));
    B     = asin(cos(L)*cos(delta)*cos(H) + sin(L)*sin(delta));
    cosB  = cos(B);

    if abs(cosB) > 1e-10
        azi_s = asin(max(-1, min(1, cos(delta)*sin(H)/cosB)));
    else
        azi_s = 0;
    end

    P_total = 0;

    if B > -theta_dip
        for p = 1:panel_number
            cos_theta = cos(B)*cos(azi_s - azi_p(p))*sin(E) + sin(B)*cos(E);
            if cos_theta > 0
                G_panel    = G_sc * cos_theta * I_illum;
                panel_area = panel_widths(p) * panel_height(p) - obstructions(p);
                P_total    = P_total + G_panel * panel_area * panel_eff * inc_derate;
            end
        end
    end

    P_solar_now = P_total;

    % CHECK IF MISSION COMPLETE
    if current_distance >= total_distance_goal
        driving = false;
    else
        driving = true;
    end

    % PAYLOAD DROP LOGIC
    if next_payload_index <= length(payload_drop_distances)
        if current_distance >= payload_drop_distances(next_payload_index)
            payloads_remaining = payloads_remaining - 1;
            next_payload_index = next_payload_index + 1;
        end
    end

    % SCIENCE STOP LOGIC
    % Priority: science > charging > driving
    % Trigger when distance crosses the scheduled stop distance.
    % End when elapsed time at stop reaches the scheduled duration.
    if ~in_science && next_science_index <= num_science_stops && ...
            current_distance >= science_stops_dist(next_science_index)
        in_science           = true;
        science_time_elapsed = 0;
        in_charging          = false;   % cancel any active charge stop
        fprintf('Science stop %d started at t=%.2f hr, d=%.1f m\n', ...
            next_science_index, t(i), current_distance);
    end

    if in_science
        science_time_elapsed = science_time_elapsed + dt;
        if science_time_elapsed >= science_stop_times(next_science_index)
            fprintf('Science stop %d complete at t=%.2f hr\n', ...
                next_science_index, t(i));
            in_science         = false;
            next_science_index = next_science_index + 1;
        end
    end

    % SOC-BASED CHARGING LOGIC
    if ~in_charging && ~in_science && driving && ...
            SOC(i-1) <= charge_start_fraction * E_batt_capacity
        in_charging = true;
    end

    if in_charging && ...
            SOC(i-1) >= charge_stop_fraction * E_batt_capacity
        in_charging = false;
    end


    % DETERMINE OPERATING MODE
    % Priority: science > charging > driving > idle
    if in_science
        P_mode      = P_av_rest;   % motors off during science stop
        driving_now = false;
    elseif in_charging
        P_mode      = P_av_rest;
        driving_now = false;
    elseif driving
        P_mode      = P_motors + P_av_travel;
        driving_now = true;
    else
        P_mode      = P_av_rest;
        driving_now = false;
    end


    % PAYLOAD POWER
    % Science stops use payload_science_power instead of normal payload power.
    if in_science
        P_payload = payload_science_power;
    else
        P_payload = payloads_remaining * (payload_total_power_n / num_of_payloads);
    end


    % TOTAL LOAD
    P_load = P_mode + P_payload + P_heaters;

    % UPDATE DISTANCE
    % Path only advances when actually driving — pauses during charging.
    if driving_now
        distance(i) = current_distance + speed * dt * 3600;
    else
        distance(i) = current_distance;
    end

    % LOG FOR VISUALISATION
    illum_log(i)    = I_illum;
    charging_log(i) = in_charging;
    P_solar_log(i)  = P_solar_now;
    science_log(i)  = in_science;

    % SOC UPDATE
    P_net  = P_solar_now - P_load;
    SOC(i) = SOC(i-1) + P_net * dt;

    % BATTERY LIMITS
    if SOC(i) > E_batt_capacity
        SOC(i) = E_batt_capacity;
    end

    if SOC(i) <= 0
        SOC(i)         = 0;
        mission_failed = true;
        fprintf('Mission failure at t=%.2f hr, distance=%.1f m\n', t(i), distance(i));
    end

end

%% RESULTS

min_SOC = min(SOC);
max_SOC = max(SOC);

fprintf('Minimum SOC (Wh): %.2f\n', min_SOC);
fprintf('Maximum SOC (Wh): %.2f\n', max_SOC);

if mission_failed
    failure_time = t(find(SOC == 0, 1));
    failure_dist = distance(find(SOC == 0, 1));
    fprintf('MISSION FAILURE: battery depleted at t=%.2f hr, d=%.1f m\n', ...
        failure_time, failure_dist);
    fprintf('Rover permanently non-operational after this point.\n');
else
    fprintf('Mission feasible with this battery mass.\n');
end

if distance(end) < total_distance_goal
    fprintf('WARNING: Distance goal not reached (%.1f / %.1f m).\n', ...
        distance(end), total_distance_goal);
else
    fprintf('Distance goal reached.\n');
end

%% PLOTS

close all;   % ensure no stale figures from previous runs

% --- Fig 1: SOC vs Time (dated at this point but still used) ---
figure;
plot(t, SOC, 'LineWidth', 2)
xlabel('Time [hr]')
ylabel('Battery Energy (Wh)')
title('Battery SOC vs Time')
grid on

% --- Fig 2: Distance vs Time (dated at this point but still used) ---
figure;
plot(t, distance, 'LineWidth', 2)
xlabel('Time [hr]')
ylabel('Distance Traveled [m]')
title('Distance vs Time')
grid on

% --- Fig 3: SOC + Illumination/Charging overlay ---
% Grey shading  = rover is in shadow (no solar input)
% Blue shading  = rover has stopped to charge
% Both overlapped: charging stop in shadow BAD!
fig1 = figure;
hold on

in_shadow    = illum_log == 0;
shadow_starts = find(diff([0  in_shadow     ]) ==  1);
shadow_ends   = find(diff([   in_shadow   0 ]) == -1);
for k = 1:length(shadow_starts)
    xp = [t(shadow_starts(k)) t(shadow_ends(k)) t(shadow_ends(k)) t(shadow_starts(k))];
    yp = [0 0 E_batt_capacity E_batt_capacity];
    patch(xp, yp, [0.85 0.85 0.85], 'EdgeColor', 'none', 'FaceAlpha', 0.5)
end

charge_starts = find(diff([0  double(charging_log)  ]) ==  1);
charge_ends   = find(diff([   double(charging_log) 0]) == -1);
for k = 1:length(charge_starts)
    xp = [t(charge_starts(k)) t(charge_ends(k)) t(charge_ends(k)) t(charge_starts(k))];
    yp = [0 0 E_batt_capacity E_batt_capacity];
    patch(xp, yp, [0.6 0.8 1.0], 'EdgeColor', 'none', 'FaceAlpha', 0.4)
end

plot(t, SOC, 'k-', 'LineWidth', 2)

science_starts = find(diff([0  double(science_log)  ]) ==  1);
science_ends   = find(diff([   double(science_log) 0]) == -1);
for k = 1:length(science_starts)
    xp = [t(science_starts(k)) t(science_ends(k)) t(science_ends(k)) t(science_starts(k))];
    yp = [0 0 E_batt_capacity E_batt_capacity];
    patch(xp, yp, [0.2 0.7 0.3], 'EdgeColor', 'none', 'FaceAlpha', 0.35)
end

h1 = patch(NaN, NaN, [0.85 0.85 0.85], 'EdgeColor', 'none', 'FaceAlpha', 0.5);
h2 = patch(NaN, NaN, [0.6  0.8  1.0 ], 'EdgeColor', 'none', 'FaceAlpha', 0.4);
h3 = patch(NaN, NaN, [0.2  0.7  0.3 ], 'EdgeColor', 'none', 'FaceAlpha', 0.35);
h4 = plot(NaN, NaN, 'k-', 'LineWidth', 2);
legend([h1 h2 h3 h4], {'In shadow', 'Charging stop', 'Science stop', 'SOC'}, 'Location', 'best')
xlabel('Time [hr]')
ylabel('Battery Energy (Wh)')
title(sprintf('October %.0f, 2027\nSOC vs Time  |  Grey = shadow, Blue = charging stop', day))
ylim([0 E_batt_capacity * 1.05])
grid on

filename = sprintf('SOC_Oct%02.0f_2027.jpg', day);
fprintf('Saving: %s\n', filename);
exportgraphics(fig1, filename, 'Resolution', 300);
close(fig1)

hold off

% --- Fig 4: Distance vs Time coloured by illumination ---
fig2 = figure;
hold on

sun_mask    = illum_log == 1;          % logical, length N
shadow_mask = ~sun_mask;

% Build distance vectors with NaN wherever the condition is NOT met
dist_sun    = distance;  dist_sun(shadow_mask) = NaN;
dist_shadow = distance;  dist_shadow(sun_mask) = NaN;

plot(t, dist_sun,    '-', 'Color', [0.95 0.75 0.1], 'LineWidth', 1.5)
plot(t, dist_shadow, '-', 'Color', [0.35 0.35 0.55], 'LineWidth', 1.5)

legend({'Sunlit', 'Shadow'}, 'Location', 'best')
xlabel('Time [hr]')
ylabel('Distance Traveled [m]')
title(sprintf('October %.0f, 2027\nDistance vs Time  |  Yellow = sunlit, Blue = shadow', day))
grid on

filename = sprintf('Dist_Oct%02.0f_2027.jpg', day);
fprintf('Saving: %s\n', filename);
exportgraphics(fig2, filename, 'Resolution', 300);
close(fig2)

hold off